### ISSUE TITLE
Stacking recurrent layers

### ISSUE THREAD

**Issue by kjancsi** [IndicoDataSolutions/Passage#17]
I get dimension mismatch error when trying to stack recurrent layers (LSTM or Gated) to create a deep recurrent network. Multiple dense layers seem to work fine though.

**Comment by Newmu** [comment]
All but the last recurrent layer should have the seq_output argument set to True.

Example layer config:

``` python
layers = [
    Embedding(size=128, n_features=1000),
    GatedRecurrent(size=256, seq_output=True),
    GatedRecurrent(size=256, seq_output=True),
    GatedRecurrent(size=256, seq_output=False),
    Dense(size=1, activation='sigmoid')
]
```

**Comment by kjancsi** [comment]
That makes sense. Thanks a lot for the clarification.
