### ISSUE TITLE
Stroing trained model

### ISSUE THREAD

**Issue by agogolev** [IndicoDataSolutions/Passage#4]
Hello,

What is the proper way to store and restore the trained model?
I tried to pickle the model variable but stuck with following error:

```
*** PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
```

I bet you don't retrain the whole network on each run. How do you store it?

**Comment by Newmu** [comment]
Yep, we have load and save interfaces. 

Please see https://github.com/IndicoDataSolutions/Passage/issues/1 for previous comments.

**Comment by agogolev** [comment]
@Newmu 

Thanks!
