### ISSUE TITLE
Would it be possible for you to dump a small data file for use with the examples?

### ISSUE THREAD

**Issue by simonhughes22** [IndicoDataSolutions/Passage#8]
I'd like to run the example code to step through the code to better understand how to use it and how it works. Could you provide the data file used in samples or a link to it, or some other small dataset and code to run the algorithm on? Looks like an awesome tool, and pretty simple to use.

**Comment by Slater-Victoroff** [comment]
Ah, that makes total sense. The data file was mentioned in the talk for the release of the library here: https://www.youtube.com/watch?v=VINCQghQRuM, but it really should be added here. I'll probably add a PR for this later today.
